PUT http://localhost:5000/api/users/bio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzcyMTA4MDAxLCJleHAiOjE3NzIxMTE2MDF9.lUTi9kqPBQF2_6kkrg2z03JJ65nUcXLgIEt0iV5cIpg
Content-Type: application/json

{ "bio": "Web developer with heart of gold" }