PUT http://localhost:5000/api/users/username
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzcyMTA3OTMyLCJleHAiOjE3NzIxMTE1MzJ9.jxgiwQhFreZr0wT3zhhjHzxCPrR9gV3J9HSpKaIMZmc
Content-Type: application/json

{ "username": "Shade" }