### Delete a user by ID
DELETE http://localhost:5000/api/users/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzcxOTE4NTU5LCJleHAiOjE3NzE5MjIxNTl9.SMG05p_5ZmDEQP-rZ_uv-OjElcHnpFjVilOVVfNZEkw
Content-Type: application/json